# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8e21c5d5d52e44e68c429634cd564ca9"
name = "QRCode-Adhurim Berisha"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders ,write_metaobjects,write_metaobject_definitions,write_app_proxy, write_discounts, write_cart_transforms"

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.qrcode]
name = "QR Code"
description = "QR codes that link to products"

  [metaobjects.app.qrcode.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[metaobjects.app.qrcode.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.qrcode.fields.product]
name = "Product"
type = "product_reference"

[metaobjects.app.qrcode.fields.product_variant]
name = "Product Variant"
type = "variant_reference"

[metaobjects.app.qrcode.fields.destination]
name = "Destination"
type = "single_line_text_field"

[metaobjects.app.qrcode.fields.scans]
name = "Scans"
type = "number_integer"

[app_proxy]
url = "/qrcodes"
subpath = "qrcodes"
prefix = "apps"


[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  # Delivered to Google Pub/Sub.
  # Grant delivery@shopify-pubsub-webhooks.iam.gserviceaccount.com Pub/Sub Publisher.
  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "pubsub://ltc-we:LTC-webhooks"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
