query DeliveryInput {
  cart {
    attribute(key: "src") {
      value
    }
    retailLocation {
      id
    }
    buyerIdentity {
      isAuthenticated
      customer {
        qrDiscountRedeemed: metafield(
          namespace: "$app"
          key: "qr_discount_redeemed"
        ) {
          jsonValue
        }
      }
    }
    deliveryGroups {
      id
    }
  }
  discount {
    discountClasses
    metafield(namespace: "$app", key: "function-configuration") {
      value
    }
  }
  localization {
    language {
      isoCode
    }
  }
}
