query CartInput($collectionIds: [ID!]) {
  cart {
    attribute(key: "src") {
      value
    }
    retailLocation {
      id
    }
    buyerIdentity {
      isAuthenticated
      customer {
        qrDiscountRedeemed: metafield(
          namespace: "$app"
          key: "qr_discount_redeemed"
        ) {
          jsonValue
        }
      }
    }
    lines {
      id
      qrSrc: attribute(key: "src") {
        value
      }
      cost {
        subtotalAmount {
          amount
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          product {
            inAnyCollection(ids: $collectionIds)
          }
        }
      }
    }
  }
  discount {
    discountClasses
    metafield(namespace: "$app", key: "function-configuration") {
      value
    }
  }
  localization {
    language {
      isoCode
    }
  }
}
